### ISSUE TITLE
Failed to load the npm-docs package

### ISSUE THREAD

**Issue by JonnyHayes** [jclem/npm-docs#11]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [npm-docs](https://github.com/jclem/npm-docs) package, v0.2.0

### Stack Trace

Failed to load the npm-docs package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/jonhayes/.atom/packages/npm-docs/lib/npm-docs-view.coffee:4:199)
    at /Users/jonhayes/.atom/packages/npm-docs/lib/npm-docs-view.coffee:9:5
    at Object.<anonymous> (/Users/jonhayes/.atom/packages/npm-docs/lib/npm-docs-view.coffee:66:5)
    at Object.<anonymous> (/Users/jonhayes/.atom/packages/npm-docs/lib/npm-docs-view.coffee:68:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jonhayes/.atom/packages/npm-docs/lib/npm-docs.coffee:12:17)
    at Object.<anonymous> (/Users/jonhayes/.atom/packages/npm-docs/lib/npm-docs.coffee:93:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:743:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "angularjs-helper"
    ],
    "projectHome": "/Users/jonhayes/Sites"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.4
angularjs-snippets, v0.10.18
foundation5-snippets, v0.2.2
language-cfml, v0.13.0
node-debugger, v1.7.0
node-resolver, v1.0.1
npm-docs, v0.2.0
php-twig, v4.0.0
project-manager, v2.9.7
vim-mode, v0.65.1

# Dev
No dev packages
```

**Comment by siliconchris1973** [comment]
> I just started ATOM for the very first time and tried to install some packages.

**Comment by mrjcleaver** [comment]
I get this too

**Comment by siliconchris1973** [comment]
Me too? Any updates?

**Comment by takotuesday** [comment]
+1

**Comment by D2Edev** [comment]
same error

**Comment by nayefmhmd** [comment]
xxxx

**Comment by animeshsinghweb** [comment]
yet the same bug here

**Comment by sleepdefic1t** [comment]
same
```macOS 10.12.6``` 
```Atom 1.18.0 x64``` 
![screen shot 2017-07-19 at 7 42 33 am](https://user-images.githubusercontent.com/7477456/28365277-e1414ac4-6c55-11e7-920c-2f1894316853.png)

**Comment by haykam821** [comment]
Same error here.

**Comment by Latigresa** [comment]
same here

**Comment by juanalbglz** [comment]
same here

**Comment by prettyamfora** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [npm-docs](https://github.com/jclem/npm-docs) package 0.2.0


### Stack Trace

Failed to load the npm-docs package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at extend (/packages/npm-docs/lib/npm-docs-view.coffee:1:1)
    at /packages/npm-docs/lib/npm-docs-view.coffee:4:7
    at /packages/npm-docs/lib/npm-docs-view.coffee:32:13)
    at /packages/npm-docs/lib/npm-docs-view.coffee:1:1)
    at /packages/npm-docs/lib/npm-docs-view.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:146745)
    at /packages/npm-docs/lib/npm-docs.coffee:5:15)
    at /packages/npm-docs/lib/npm-docs.coffee:1:1)
    at /packages/npm-docs/lib/npm-docs.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:1:721712)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3299000)
    at measure (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3285540)
    at Package.measure (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3284372)
    at Package.load (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3285113)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:381274)
    at PackageManager.loadPackage (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:380002)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:382574)
    at ~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:943557
    at r (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:938163)
    at o (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1122275)
    at t.bufferStream (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1122429)
    at Socket.e.on (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:1121031)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12)
```

### Commands

```
     -9:38.6.0 core:move-down (input.hidden-input)
  3x -9:36.2.0 core:backspace (input.hidden-input)
     -9:25.1.0 core:confirm (input.hidden-input)
     -9:25.1.0 command-palette:show-hidden-commands (ul.list-inline.tab-bar.inset-panel)
     -9:18.9.0 core:confirm (input.hidden-input)
  4x -9:17.6.0 core:backspace (input.hidden-input)
     -8:59.9.0 dev-live-reload:reload-all (ul.list-inline.tab-bar.inset-panel)
     -8:27.3.0 markdown-preview:toggle-github-style (ul.list-inline.tab-bar.inset-panel)
     -8:11.1.0 open-on-github:repository (ul.list-inline.tab-bar.inset-panel)
     -7:57.4.0 settings-view:install-packages-and-themes (ul.list-inline.tab-bar.inset-panel)
  3x -5:19 core:move-left (input.hidden-input)
  4x -5:18.2.0 core:move-right (input.hidden-input)
 10x -5:16.6.0 core:backspace (input.hidden-input)
  3x -4:04.0 core:confirm (input.hidden-input)
 27x -2:55.9.0 core:backspace (input.hidden-input)
     -2:41.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.18 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atom-npm 0.3.1 
hey-pane 1.2.0 
Hydrogen 2.14.1 
language-caper 1.1.0 
my-package 0.0.0 
npm 2.0.0 
npm-docs 0.2.0 
npm-init 1.1.0 
npm-plus 0.4.0 
npm-start 0.5.0 
package-json5 1.0.1 
scroll-through-time 0.3.1 
teletype 0.13.4 
zentabs 0.8.9 
```

**Comment by prettyamfora** [comment]
Installing “language-tenableaudits@0.0.17” failed.Hide output…

> sitter-tenableaudits@0.0.9 install C:\Users\deby\AppData\Local\Temp\apm-install-dir-12046-10088-10cjpi0.2pua\node_modules\language-tenableaudits\node_modules\sitter-tenableaudits
> node-gyp rebuild


C:\Users\deby\AppData\Local\Temp\apm-install-dir-12046-10088-10cjpi0.2pua\node_modules\language-tenableaudits\node_modules\sitter-tenableaudits>if not defined npm_config_node_gyp (node "C:\Users\deby\AppData\Local\atom\app-1.46.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\deby\AppData\Local\atom\app-1.46.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\deby\AppData\Local\atom\app-1.46.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\deby\AppData\Local\atom\app-1.46.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\deby\AppData\Local\atom\app-1.46.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\deby\\AppData\\Local\\atom\\app-1.46.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\deby\\AppData\\Local\\atom\\app-1.46.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\deby\AppData\Local\Temp\apm-install-dir-12046-10088-10cjpi0.2pua\node_modules\language-tenableaudits\node_modules\sitter-tenableaudits
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN rollback Rolling back normalize-package-data@2.5.0 failed (this is probably harmless): EPERM: operation not permitted, scandir 'C:\Users\deby\AppData\Local\Temp\apm-install-dir-12046-10088-10cjpi0.2pua\node_modules\language-tenableaudits\node_modules\npm\node_modules'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\deby\AppData\Local\Temp\apm-install-dir-12046-10088-10cjpi0.2pua\package.json'
npm WARN apm-install-dir-12046-10088-10cjpi0.2pua No description
npm WARN apm-install-dir-12046-10088-10cjpi0.2pua No repository field.
npm WARN apm-install-dir-12046-10088-10cjpi0.2pua No README data
npm WARN apm-install-dir-12046-10088-10cjpi0.2pua No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sitter-tenableaudits@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sitter-tenableaudits@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\deby\.atom\.apm\_logs\2020-05-06T18_52_58_157Z-debug.log

Installing “eez-studio@0.2.6” failed.Hide output…

npm ERR! code E400
npm ERR! 400 Bad Request: https://www.atom.io/api/packages/eez-studio/versions/0.2.6/tarball

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\deby\.atom\.apm\_logs\2020-05-06T18_57_01_204Z-debug.log

Installing “eez-studio@0.2.6” failed.Hide output…

npm ERR! code E400
npm ERR! 400 Bad Request: https://www.atom.io/api/packages/eez-studio/versions/0.2.6/tarball

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\deby\.atom\.apm\_logs\2020-05-06T18_57_15_504Z-debug.log
