### ISSUE TITLE
Failed to load the npm-docs package

### ISSUE THREAD

**Issue by mazzy89** [jclem/npm-docs#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [npm-docs](https://github.com/jclem/npm-docs) package, v0.2.0
### Stack Trace

Failed to load the npm-docs package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/mazzy/.atom/packages/npm-docs/lib/npm-docs-view.coffee:4:199)
    at /Users/mazzy/.atom/packages/npm-docs/lib/npm-docs-view.coffee:9:5
    at Object.<anonymous> (/Users/mazzy/.atom/packages/npm-docs/lib/npm-docs-view.coffee:66:5)
    at Object.<anonymous> (/Users/mazzy/.atom/packages/npm-docs/lib/npm-docs-view.coffee:68:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete",
      "todo-show",
      "toolbar"
    ],
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.2.0
atom-django, v0.2.1
autocomplete-plus, v2.12.0
chester-atom-syntax, v0.1.1
emmet, vundefined
file-icons, v1.5.4
jsdoc, v0.9.0
language-docker, v1.1.3
language-jade, v0.4.0
language-nginx, v0.5.1
language-svg, v0.8.0
language-terraform, v0.4.0
linter, v0.12.1
linter-jshint, v0.1.2
minimap, v4.7.6
npm-docs, v0.2.0
react, v0.11.6
script, v2.19.0
svg-preview, v0.5.1

# Dev
No dev packages
```

**Comment by rogozhnikov** [comment]
The same problem by me...

**Comment by LambertPark** [comment]
The same problem by me...

**Comment by epappas** [comment]
Same here...

**Comment by halhenke** [comment]
Been having this for about a couple of weeks now:

Steps to Reproduce

1. Open up Atom/a new window in Atom

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [npm-docs](https://github.com/jclem/npm-docs) package, v0.2.0


### Stack Trace

Failed to load the npm-docs package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/hal/.atom/packages/npm-docs/lib/npm-docs-view.coffee:1:1)
    at /Users/hal/.atom/packages/npm-docs/lib/npm-docs-view.coffee:5:3
    at Object.<anonymous> (/Users/hal/.atom/packages/npm-docs/lib/npm-docs-view.coffee:5:3)
    at Object.<anonymous> (/Users/hal/.atom/packages/npm-docs/lib/npm-docs-view.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/hal/.atom/packages/npm-docs/lib/npm-docs.coffee:5:15)
    at Object.<anonymous> (/Users/hal/.atom/packages/npm-docs/lib/npm-docs.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:661:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:115:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:386:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:667:21)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:38:8)
    at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:49:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:79:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "repeat-command",
      "tab-switcher",
      "linter-jshint",
      "terminal-runner",
      "atom-xikij",
      "symbols-view",
      "atom-speech-to-code"
    ],
    "themes": [
      "isotope-ui",
      "atom-dark-syntax"
    ],
    "destroyEmptyPanes": false,
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "tmp"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
angularjs, v0.3.3
atom-ctags, v4.4.1
atom-typescript, v7.11.0
atom-yeoman, v0.3.15
atomatigit, v1.5.5
bower-install, v0.2.4
coffee-compile, v0.19.2
color-picker, v2.0.13
command-logger, v0.23.0
ember-cli-helper, v0.9.0
ember-snippets, v1.4.0
file-types, v0.5.1
gulp-snippets, v0.6.2
isotope-ui, v2.7.0
javascript-snippets, v1.0.0
jslint, v1.5.1
language-ansible, v0.1.3
language-applescript, v0.2.0
language-babel, v2.5.0
language-diff, v0.4.0
language-docker, v1.1.3
language-fish-shell, v1.0.2
language-haml, v0.23.6
language-haskell, v1.5.0
language-jade, v0.6.2
language-nginx, v0.6.1
language-yaml, v0.24.0
line-jumper, v0.14.1
linter, v1.11.1
linter-eslint, v5.1.0
linter-rubocop, v0.4.4
npm-docs, v0.2.0
pain-split, v1.4.0
project-manager, v2.6.5
quippet, v2.0.0
react, v0.12.10
regex-railroad-diagram, v0.10.4
release-notes, v0.53.0
ruby-block, v0.3.5
ruby-block-converter, v3.5.0
set-syntax, v0.3.0
starred-package-installer, v0.1.0
tabs-to-spaces, v0.11.1
word-jumper, v0.3.0
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by JerrySievert** [comment]
Any progress on this?

**Comment by moustachedelait** [comment]
this is getting really old, on every startup I get this

**Comment by esd100** [comment]
same problem here.

**Comment by cbrunnkvist** [comment]
me too :bomb:

**Comment by esd100** [comment]
same problem...

```
 TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/esd100/.atom/packages/npm-docs/lib/npm-docs-view.coffee:4:199)
    at /Users/esd100/.atom/packages/npm-docs/lib/npm-docs-view.coffee:9:5
    at Object.<anonymous> (/Users/esd100/.atom/packages/npm-docs/lib/npm-docs-view.coffee:66:5)
    at Object.<anonymous> (/Users/esd100/.atom/packages/npm-docs/lib/npm-docs-view.coffee:68:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/esd100/.atom/packages/npm-docs/lib/npm-docs.coffee:12:17)
    at Object.<anonymous> (/Users/esd100/.atom/packages/npm-docs/lib/npm-docs.coffee:93:4)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:663:34)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:115:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:438:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:390:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:682:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

**Comment by jclem** [comment]
Anyone want to take this over? I've stopped using Atom :(

**Comment by faddah** [comment]
+1 on Atom v1.4.1 & Mac OS X 10.11.3 el capitan, still cannot load nom-docs.

**Comment by mburger89** [comment]
me as well.

**Comment by mixmatch** [comment]
+1

**Comment by carbonecar** [comment]
I have the same problem too :(

**Comment by SkonTeam** [comment]
Guys i patched this package to work with the latest atom api : [SkonTeam/npm-docs](https://github.com/SkonTeam/npm-docs) .

As i don't know how to publish it to apm registry just clone it and copy-paste into your atom packages dir replacing the original package.

## Usage : 
Select package name and from the command palette launch either of the options : npm-doc Readme , open or homepage. (also accessible from menu bar).

**Comment by zeke** [comment]
@SkonTeam nice work! Why don't you open a pull request? Pretty sure we can get @jclem to publish a new version of the atom package.

**Comment by zeke** [comment]
Oh you did already! https://github.com/jclem/npm-docs/pull/10

**Comment by moorage** [comment]
@jclem wanna accept #10 :)

**Comment by artivilla** [comment]
@SkonTeam tried manually copying this into my atom dir under /.atom/packages and running 'apm link' that gives me `/Users/av/.atom/packages/packages -> /Users/av/.atom/packages` and then restarting atom. Am I installing this incorrectly?

## Stack Trace

```
Cannot find module 'open'
Hide Stack Trace
Error: Cannot find module 'open'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/artichandok/.atom/packages/npm-docs/lib/npm-docs.coffee:1:15)
    at Object.<anonymous> (/Users/artichandok/.atom/packages/npm-docs/lib/npm-docs.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:743:28
```

Running OSX 10.11.15
$ apm -v
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.7.4
