### ISSUE TITLE
Failed to activate the npm-docs package

### ISSUE THREAD

**Issue by Gebriel** [jclem/npm-docs#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Microsoft Windows 10 Enterprise N 2015 LTSB
**Thrown From**: [npm-docs](https://github.com/jclem/npm-docs) package, v0.2.0

### Stack Trace

Failed to activate the npm-docs package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (C:\Users\mpc\.atom\packages\npm-docs\lib\npm-docs-view.coffee:1:1)
  at C:\Users\mpc\.atom\packages\npm-docs\lib\npm-docs-view.coffee:5:3
  at Object.<anonymous> (C:\Users\mpc\.atom\packages\npm-docs\lib\npm-docs-view.coffee:66:5)
  at Object.<anonymous> (C:\Users\mpc\.atom\packages\npm-docs\lib\npm-docs-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\mpc\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\mpc\.atom\packages\npm-docs\lib\npm-docs.coffee:5:15)
  at Object.<anonymous> (C:\Users\mpc\.atom\packages\npm-docs\lib\npm-docs.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\mpc\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\mpc\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:759:34)
  at Package.module.exports.Package.activateConfig (C:\Users\mpc\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:261:14)
  at Package.module.exports.Package.activateNow (C:\Users\mpc\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:239:14)
  at C:\Users\mpc\AppData\Local\atom\app-1.0.7\resources\app.asar\src\package.js:836:25
  at Emitter.module.exports.Emitter.emit (C:\Users\mpc\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\mpc\AppData\Local\atom\app-1.0.7\resources\app.asar\src\command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (C:\Users\mpc\AppData\Local\atom\app-1.0.7\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\mpc\AppData\Local\atom\app-1.0.7\resources\app.asar\src\command-registry.js:156:19)
  at EventEmitter.<anonymous> (C:\Users\mpc\AppData\Local\atom\app-1.0.7\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:04.9.0 npm-docs:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.5.21
autosave-plus, v0.5.2
javascript-snippets, v1.0.0
minimap, v4.12.3
node-debugger, v1.1.8
npm-docs, v0.2.0
save-session, v0.15.7

# Dev
No dev packages
```

**Comment by gfarrell** [comment]
Same problem here, but looks like this project isn't maintained...

**Comment by esd100** [comment]
What is the status of this? This has been unresolved for about 6 months now.

**Comment by pattch** [comment]
I still have this problem as well, any news? 

[Enter steps to reproduce below:]

1. Open Atom
2. Error Message Appears

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11.3
**Thrown From**: [npm-docs](https://github.com/jclem/npm-docs) package, v0.2.0


### Stack Trace

Failed to load the npm-docs package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/Sam/.atom/packages/npm-docs/lib/npm-docs-view.coffee:1:1)
    at /Users/Sam/.atom/packages/npm-docs/lib/npm-docs-view.coffee:5:3
    at Object.<anonymous> (/Users/Sam/.atom/packages/npm-docs/lib/npm-docs-view.coffee:5:3)
    at Object.<anonymous> (/Users/Sam/.atom/packages/npm-docs/lib/npm-docs-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Sam/.atom/packages/npm-docs/lib/npm-docs.coffee:5:15)
    at Object.<anonymous> (/Users/Sam/.atom/packages/npm-docs/lib/npm-docs.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
language-mongodb, v0.3.1
npm-docs, v0.2.0
tabs-to-spaces, v1.0.2

# Dev
No dev packages
```
